services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  app:
    image: movie_api
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py