services:
  
  db:
    #Hosts postgres db on port 5432
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    #used for managing SQL database via web
    #https://www.adminer.org/
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
  app:
    #on command runs script for getting and storing data
    image: movie_api_1_1_1
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py